from .categorias.categoria_create import CategoriaCreateDto
from .categorias.categoria_delete_response import CategoriaDeleteResponseDto
from .relatos.relato_create_dto import  RelatoCreateDto
from .relatos.relato_delete_response import RelatoDeleteResponseDto
from .relatos.relato_batch_response import RelatoBatchResponseDto