"""Remove user fields

Revision ID: 71f85339cdfc
Revises: 1e0ce13d746a
Create Date: 2025-10-07 17:32:03.662659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71f85339cdfc'
down_revision: Union[str, Sequence[str], None] = '1e0ce13d746a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('keycloak_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_usuario_google_auth_user_id'), table_name='usuario')
    op.create_index(op.f('ix_usuario_keycloak_id'), 'usuario', ['keycloak_id'], unique=True)
    op.drop_column('usuario', 'google_auth_user_id')
    op.drop_column('usuario', 'senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('google_auth_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usuario_keycloak_id'), table_name='usuario')
    op.create_index(op.f('ix_usuario_google_auth_user_id'), 'usuario', ['google_auth_user_id'], unique=True)
    op.drop_column('usuario', 'keycloak_id')
    # ### end Alembic commands ###
